Update Trivy-Adapter README
kubernetes-sigs/wg-policy-prototypes pull request #107
Opened 2022-04-10 13:10 UTC by adeniyistephen

Fix: I updated the third step on using trivy-adapter from: "Create a vulnerability report customResourceDefinition" to "Create resources in the cluster that trivy-adapter will use"

2022-04-10 17:27 UTC, JimBugwadia requested changes

2022-04-10 17:27 UTC, JimBugwadia commented on policy-report/trivy-adapter/README.md
>  #### Road Maps:
Change to "Roadmap"

2022-04-10 18:25 UTC, adeniyistephen commented on policy-report/trivy-adapter/README.md
>  #### Road Maps:
Done.

2022-04-10 18:45 UTC, JimBugwadia approved these changes

2022-04-10 19:36 UTC, adeniyistephen commented
LGTM

2022-04-12 22:28 UTC, JimBugwadia commented
/lgtm
/approve

2022-04-12 22:28 UTC, merged