Add a top level policy engine identifier
kubernetes-sigs/wg-policy-prototypes pull request #121
Opened 2023-03-15 13:49 UTC by anusha94

Added an optional `Source` field at the `PolicyReport` level. Use this field if a single policy engine is responsible for producing results in a single `PolicyReport`.

Fixes #116

2023-03-17 03:45 UTC, kumar-mallikarjuna approved these changes
lgtm

2023-03-17 03:46 UTC, kumar-mallikarjuna approved these changes

2023-03-17 07:14 UTC, JimBugwadia reviewed
Looks good! Minor suggestions on the descriptions.

2023-03-17 07:14 UTC, JimBugwadia commented on policy-report/crd/v1beta1/wgpolicyk8s.io_policyreports.yaml
> +              policy engine. If multiple policy engines are producing results in a
change `policy engine` to `source e.g. a policy engine.`

2023-03-17 07:14 UTC, JimBugwadia commented on policy-report/pkg/api/wgpolicyk8s.io/v1beta1/policyreport_types.go
> +	// Use this field if all the results are produced by a single policy engine.
change policy engine to source e.g. a policy engine.

2023-03-17 07:14 UTC, JimBugwadia commented on policy-report/pkg/api/wgpolicyk8s.io/v1beta1/policyreport_types.go
> +	// If multiple policy engines are producing results in a single PolicyReport,
If the results are produced by multiple sources e.g. different engines or scanners, use...

2023-03-17 07:18 UTC, JimBugwadia requested changes
added a few minor suggestions

2023-03-18 03:49 UTC, JimBugwadia approved these changes

2023-03-18 03:50 UTC, JimBugwadia commented
/approve
/lgtm

2023-03-18 03:51 UTC, merged