Remove uniqueItems from statusFilter
kubernetes-sigs/wg-policy-prototypes pull request #129
Opened 2024-02-26 21:53 UTC by anusha94

2024-02-28 07:41 UTC, JimBugwadia requested changes
Looks like an older version (v0.9.0) of controller-gen was used, can you please try with the latest or v0.12.1 (the one previously used)?

2024-02-28 09:34 UTC, anusha94 commented
> Looks like an older version (v0.9.0) of controller-gen was used, can you please try with the latest or v0.12.1 (the one previously used)?

Yea I changed back to what was being used, and removed other `go.mod` related changes as well.

Tested by installing this CRD on a kind cluster, and it works fine.

2024-02-29 19:34 UTC, JimBugwadia approved these changes

2024-02-29 19:34 UTC, JimBugwadia commented
/lgtm
/approve

2024-02-29 19:41 UTC, merged