Adds kubearmor-adapter to generate and update policyreports based on Policy Report CRD
kubernetes-sigs/wg-policy-prototypes pull request #95
Opened 2021-11-30 05:39 UTC by haardikdharma10

This PR aims to fix #59 

This adapter is built as a part of the [LFX Mentorship Program](https://lfx.linuxfoundation.org/tools/mentorship/) and it converts outputs received from [KubeArmor](https://github.com/kubearmor/kubearmor) and creates/updates a PolicyReport based on the Policy Report CRD.

2021-11-30 05:52 UTC, JimBugwadia requested changes
Hi @haardikdharma10 - thanks! Can you please replace the CRD and generated clientset, etc. with ones at: 

https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/pkg

2021-11-30 06:14 UTC, haardikdharma10 commented
> Hi @haardikdharma10 - thanks! Can you please replace the CRD and generated clientset, etc. with ones at:
> 
> https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/pkg

Thank you @JimBugwadia, made the necessary changes :)

2021-12-13 18:41 UTC, JimBugwadia approved these changes

2021-12-13 18:41 UTC, JimBugwadia commented
/lgtm
/approved

2021-12-13 18:42 UTC, merged